In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import os

In [4]:
dir=r'C:\Users\abalu\Desktop\data'

In [5]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [6]:
train_gen=ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range= 0.2,
    rotation_range=0.2,
    zoom_range=0.2
)

In [7]:
train_data=train_gen.flow_from_directory(
dir,
target_size=(150,150),
batch_size=32,
class_mode='binary'
)

Found 3309 images belonging to 2 classes.


In [8]:
import tensorflow as tf

In [9]:
import tensorflow.keras as kt

In [10]:
model=kt.models.Sequential()

In [11]:
model.add(kt.layers.Conv2D(32,(3,3),input_shape=(150,150,3),activation='relu'))

In [12]:
model.add(kt.layers.MaxPooling2D((2,2)))

In [13]:
model.add(kt.layers.Conv2D(64,(3,3),activation='relu'))

In [14]:
model.add(kt.layers.MaxPooling2D((2,2)))

In [15]:
model.add(kt.layers.Conv2D(128,(3,3),activation='relu'))

In [16]:
model.add(kt.layers.MaxPooling2D((2,2)))

In [17]:
model.add(kt.layers.Conv2D(128,(3,3),activation='relu'))

In [18]:
model.add(kt.layers.MaxPooling2D((2,2)))

In [19]:
model.add(kt.layers.Flatten())

In [20]:
model.add(kt.layers.Dropout(0.5))

In [21]:
model.add(kt.layers.Dense(512,activation='relu'))

In [22]:
model.add(kt.layers.Dense(1,activation='sigmoid'))

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 128)       73856     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 17, 17, 128)      0

In [24]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_data

In [27]:
model.fit_generator(train_data,steps_per_epoch=100,epochs=25)

C:\Users\abalu\AppData\Local\Temp\ipykernel_21064\2770445033.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(train_data,steps_per_epoch=100,epochs=25)


Epoch 1/25
100/100 [==============================] - 70s 695ms/step - loss: 0.6746 - accuracy: 0.5753
Epoch 2/25
100/100 [==============================] - 70s 703ms/step - loss: 0.6577 - accuracy: 0.6165
Epoch 3/25
100/100 [==============================] - 71s 703ms/step - loss: 0.6454 - accuracy: 0.6334
Epoch 4/25
100/100 [==============================] - 72s 708ms/step - loss: 0.6317 - accuracy: 0.6495
Epoch 5/25
100/100 [==============================] - 71s 708ms/step - loss: 0.6347 - accuracy: 0.6504
Epoch 6/25
100/100 [==============================] - 71s 711ms/step - loss: 0.6337 - accuracy: 0.6419
Epoch 7/25
100/100 [==============================] - 71s 711ms/step - loss: 0.6323 - accuracy: 0.6394
Epoch 8/25
100/100 [==============================] - 71s 708ms/step - loss: 0.6338 - accuracy: 0.6454
Epoch 9/25
100/100 [==============================] - 70s 701ms/step - loss: 0.6305 - accuracy: 0.6558
Epoch 10/25
100/100 [==============================] - 72s 716ms/step - l

In [28]:
import pickle

In [30]:
pickle.dump(model,open('modelman.pkl','wb'))

INFO:tensorflow:Assets written to: ram://5c5dac71-70b0-407b-ae7f-c14ab4505d0c/assets


INFO:tensorflow:Assets written to: ram://5c5dac71-70b0-407b-ae7f-c14ab4505d0c/assets


In [31]:
y=model.predict(train_data)

104/104 [==============================] - 56s 532ms/step


In [36]:
y=np.round(y)

In [39]:
y=np.argmax(y,axis=1)

In [40]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
y_pred=model.predict(train_data)

104/104 [==============================] - 54s 521ms/step


In [45]:
y_pred

array([[0.57438093],
       [0.8379696 ],
       [0.83180934],
       ...,
       [0.492071  ],
       [0.4697778 ],
       [0.84977025]], dtype=float32)

In [46]:
y_pred=np.round(y_pred,3)

In [47]:
y_pred

array([[0.574],
       [0.838],
       [0.832],
       ...,
       [0.492],
       [0.47 ],
       [0.85 ]], dtype=float32)

In [48]:
y_pred=np.round(y_pred,1)

In [49]:
y_pred

array([[0.6],
       [0.8],
       [0.8],
       ...,
       [0.5],
       [0.5],
       [0.8]], dtype=float32)

In [50]:
y_pred=np.round(y_pred)

In [52]:
y_pred.astype(int)

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [53]:
pickle.dump(model,open('model.pkl','wb'))

INFO:tensorflow:Assets written to: ram://e1e1addb-ac64-414b-8146-40ec0e5b2a90/assets


INFO:tensorflow:Assets written to: ram://e1e1addb-ac64-414b-8146-40ec0e5b2a90/assets
